#!/usr/bin/env python3
"""Pack one level's data for the Model B target, out of convert.py's own tables.

   python3 tools/assets.py [lv] [sub]     (default 3 1 = L3A, the indoor bonus level)

Emits into build/:
   tiles.bin   this level's tiles, renumbered 0..N-1, 64 bytes each
   map.bin     32x32 (or whatever the level is) of those local ids
   level.bin   header, objects, tile attributes and altitude classes
   alt.bin     altitude class rows
   spr.bin     the sprite images this level can show, with their masks
   sprtab.bin  the sprite directory, with data and mask OFFSETS from the bank base
   assets.inc  sizes and counts for the assembler
"""
import os, sys, io, contextlib, importlib.util
import numpy as np

os.environ['MODE'] = '1'
HERE = os.path.dirname(os.path.abspath(__file__))
BEEB = os.path.dirname(os.path.dirname(HERE))
os.chdir(BEEB)
spec = importlib.util.spec_from_file_location('conv', 'tools/convert.py')
m = importlib.util.module_from_spec(spec)
with contextlib.redirect_stdout(io.StringIO()):
    spec.loader.exec_module(m)
OUT = os.path.join(BEEB, 'modelb', 'build')

lv = int(sys.argv[1]) if len(sys.argv) > 1 else 3
sub = int(sys.argv[2]) if len(sys.argv) > 2 else 1
L = m.levels[(lv, sub)]
name = m.name_of(lv, sub)

# ---------------------------------------------------------------- tiles
used = sorted(set(int(t) for t in np.unique(L['map'])) - {-1})
local = {}                                  # original id -> local id
tiles = bytearray()
for o in used:
    local[o] = len(local)
    tiles += m.tiles_mode2[m.orig2compact[o]]
NTILES = len(local)
EMPTY = NTILES                              # one extra, all black, for map id -1
tiles += bytes(64)
open(os.path.join(OUT, 'tiles.bin'), 'wb').write(tiles)

# ---------------------------------------------------------------- map
mp = L['map']
h, w = mp.shape
mapb = bytearray()
for y in range(h):
    for x in range(w):
        t = int(mp[y, x])
        mapb.append(EMPTY if t < 0 else local[t])
open(os.path.join(OUT, 'map.bin'), 'wb').write(mapb)

# ---------------------------------------------------------------- level tables
hdr = bytearray([L['lw'], L['lh'], L['start'][0], L['start'][1], L['exit'][0], L['exit'][1],
                 len(L['objs']), NTILES])
for cid in [m.special['VANISH0'] + i for i in range(8)] + [m.special['FLOWER0'] + i for i in range(4)]:
    o = m.compact[cid] if cid < len(m.compact) else -1
    hdr.append(local.get(o, EMPTY))
hdr = hdr.ljust(32, b'\0')

objs = bytearray()
for (t, x, y, extra) in L['objs']:
    e = (list(extra) + [0, 0, 0])[:3]
    if t == 0:
        e[0] = 0                            # every star a plain sprite: no box stars here
        e[1] = 1
    elif t == 1:
        e[0] = 0
        e[1] = 1
    objs += bytes([t, x, y] + e)
objs = objs.ljust(256, b'\0')

attr = bytearray(256)
acls = bytearray(256)
for o, i in local.items():
    c = m.orig2compact[o]
    a = 3
    if c in m.push_tiles: a = m.push_tiles[c] + 3
    if c in m.kill_tiles: a |= 0x80
    attr[i] = a
    acls[i] = 0 if c in m.tile_solid else m.alt_class[c]
attr[EMPTY] = 3
acls[EMPTY] = 0
open(os.path.join(OUT, 'level.bin'), 'wb').write(bytes(hdr + objs + attr + acls))
open(os.path.join(OUT, 'alt.bin'), 'wb').write(bytes(m.altfile))

# ---------------------------------------------------------------- sprites
TYPE_IDS = m.TYPE_IDS
types = sorted(set(t for (t, x, y, e) in L['objs']))
ids = set(range(27)) | set(range(34, 42))
for t in types:
    if t in TYPE_IDS:
        lo, hi = TYPE_IDS[t]
        ids |= set(range(lo, hi + 1))
ALIAS = {i: 0 for i in range(22, 27)}       # fire and knockback draw the standing frame
imgs, off = {}, 0
data = bytearray()
for i in sorted(ids):
    e = m.entry[ALIAS.get(i, i)]
    if e is None: continue
    j = e[0]
    if j in imgs: continue
    imgs[j] = (len(data), len(m.img_bytes[j]))
    data += m.img_bytes[j]
maskoff = {}
for j in imgs:
    maskoff[j] = len(data)
    data += m.img_mask[j]
open(os.path.join(OUT, 'spr.bin'), 'wb').write(data)

tab = bytearray()
msk = bytearray()
for i in range(103):
    e = m.entry[ALIAS.get(i, i)]
    if e is None or e[0] not in imgs:
        tab += bytes(8); msk += bytes(2); continue
    j, mirror, rx, ry = e
    im = m.images[j][0]
    hpx, wpx = im.shape
    W = (wpx + 1) // 2
    rx += m.img_shift[j]
    if mirror:
        rx = (2 * W - 1) - rx
    do, _ = imgs[j]
    mo = maskoff[j]
    tab += bytes([do & 255, do >> 8, W, hpx, rx & 255, ry & 255,
                  (1 if mirror else 0) | 2, 2 * hpx])
    msk += bytes([mo & 255, mo >> 8])
open(os.path.join(OUT, 'sprtab.bin'), 'wb').write(tab)
open(os.path.join(OUT, 'sprmask.bin'), 'wb').write(msk)

with open(os.path.join(OUT, 'assets.inc'), 'w') as f:
    f.write('; generated by modelb/tools/assets.py from %s\n' % name)
    f.write('; level %s\n' % name)
    f.write('NTILES = %d\nEMPTYTILE = %d\n' % (NTILES, EMPTY))
    f.write('MAPW = %d\nMAPH = %d\nMAPLW = %d\nMAPLH = %d\n' % (w, h, L['lw'], L['lh']))
    f.write('NOBJS = %d\n' % len(L['objs']))
    f.write('STARTX = %d\nSTARTY = %d\n' % L['start'])
    f.write('NALTCLS = %d\n' % (len(m.altfile) // 8))
print('%s: %d tiles (%d B), map %dx%d (%d B), %d objects, sprites %d B in %d images, table %d B'
      % (name, NTILES, len(tiles), w, h, len(mapb), len(L['objs']), len(data), len(imgs), len(tab)))
