import { findJsbeeb } from "/Users/ebenupton/cleo/beeb/tools/harness.mjs";
import { pathToFileURL } from "node:url";
import { readFileSync } from "node:fs";
import path from "node:path";
const { MachineSession } = await import(pathToFileURL(findJsbeeb()));
const s = new MachineSession("B-DFS1.2");
await s.initialise(); await s.boot(30);
s.loadDisc(path.resolve("build/cleob.ssd"));
const cpu = s._machine.processor;
const lab = {}; for (const m of readFileSync("build/labels.txt", "utf8").matchAll(/^al ([0-9A-F]+) \.(\w+)$/gm)) lab[m[2]] = parseInt(m[1], 16);
const rev = {}; for (const k in lab) if (lab[k] >= 0x140 && lab[k] < 0x300) rev[lab[k]] = k;
console.log("low labels:", Object.entries(rev).map(([a, n]) => `${n}=$${(+a).toString(16)}`).join(" "));
s.keyDown(16); s.reset(true); await s.runFor(2_000_000); s.keyUp(16);
await s.runFor(4_000_000);
let t = [];
cpu.debugInstruction.add((pc) => { if (t.length < 120) t.push(pc); return false; });
await s.runFor(4000);
console.log(t.map(p => "$" + p.toString(16)).join(" "));
process.exit(0);
