import { findJsbeeb } from "/Users/ebenupton/cleo/beeb/tools/harness.mjs";
import { pathToFileURL } from "node:url";
import path from "node:path";
const { MachineSession } = await import(pathToFileURL(findJsbeeb()));
const s = new MachineSession("B-DFS1.2");
await s.initialise(); await s.boot(30);
s.loadDisc(path.resolve("build/cleob.ssd"));
const cpu = s._machine.processor;
const marks = { 0x8103: "init entry", 0x810f: "after ZP clear", 0x8131: "before init_far", 0x813e: "draw_window #1", 0x814b: "draw_window #2", 0x8154: "after both draws" };
let log = [];
cpu.debugInstruction.add((pc) => { const m = marks[pc];
  if (m && cpu.readmem(0xf4) === 7 && log.length < 10) log.push(`${m}: $17=${cpu.readmem(0x17)} $15=${cpu.readmem(0x15)} $98=${cpu.readmem(0x98)} X=${cpu.x}`);
  return false; });
s.keyDown(16); s.reset(true); await s.runFor(2_000_000); s.keyUp(16); await s.runFor(10_000_000);
console.log(log.join("\n"));
process.exit(0);
