import { findJsbeeb } from "/Users/ebenupton/cleo/beeb/tools/harness.mjs";
import { pathToFileURL } from "node:url";
import { readFileSync } from "node:fs";
import path from "node:path";
const { MachineSession } = await import(pathToFileURL(findJsbeeb()));
const s = new MachineSession("B-DFS1.2");
await s.initialise(); await s.boot(30);
s.loadDisc(path.resolve("build/cleob.ssd"));
const cpu = s._machine.processor, v = s._video;
const lab = {}; for (const m of readFileSync("build/labels.txt", "utf8").matchAll(/^al ([0-9A-F]+) \.(\w+)$/gm)) lab[m[2]] = parseInt(m[1], 16);
s.keyDown(16); s.reset(true); await s.runFor(2_000_000); s.keyUp(16);
await s.runFor(4_000_000);
let vs = 0, restarts = 0, maxrow = 0, log = [];
const oe = v.endOfFrame.bind(v); v.endOfFrame = () => { restarts++; if (log.length < 14) log.push(`restart at r${v.vertCounter}.${v.scanlineCounter} R4=${v.regs[4]} R7=${v.regs[7]} R9=${v.regs[9]} R6=${v.regs[6]}`); oe(); };
const sysvia = cpu.sysvia;
const oca = sysvia.setca1 ? sysvia.setca1.bind(sysvia) : null;
console.log("sysvia keys:", Object.keys(sysvia).filter(k => /ca1|ifr|ier|pcr/i.test(k)).join(","));
await s.runFor(400000);
console.log("restarts in 0.2s:", restarts, "; max vertCounter seen:", maxrow);
console.log(log.join("\n"));
console.log("IFR", cpu.sysvia.ifr.toString(16), "IER", cpu.sysvia.ier.toString(16), "PCR", (cpu.sysvia.pcr ?? -1).toString(16));
console.log("vsyncs var:", cpu.readmem(lab.vsyncs), "SECIDX", cpu.readmem(lab.SECIDX));
console.log("CRTC R0..R9:", v.regs.slice(0, 10).join(","), "R12/13", v.regs[12], v.regs[13]);
process.exit(0);
