import { findJsbeeb } from "/Users/ebenupton/cleo/beeb/tools/harness.mjs";
import { pathToFileURL } from "node:url";
import { readFileSync } from "node:fs";
import path from "node:path";
const { MachineSession } = await import(pathToFileURL(findJsbeeb()));
const s = new MachineSession("B-DFS1.2");
await s.initialise(); await s.boot(30);
s.loadDisc(path.resolve("build/cleob.ssd"));
const cpu = s._machine.processor;
const lab = {}; for (const m of readFileSync("build/labels.txt", "utf8").matchAll(/^al ([0-9A-F]+) \.(\w+)$/gm)) lab[m[2]] = parseInt(m[1], 16);
const watch = lab[process.argv[2] ?? "wcy"];
let hits = [], armed = false;
const ow = cpu.writemem.bind(cpu);
cpu.writemem = (a, v) => { if (armed && a === watch && hits.length < 24) hits.push(`pc=$${cpu.pc.toString(16)} <- ${v}`); return ow(a, v); };
cpu.debugInstruction.add((pc) => { if (pc === lab.init) armed = true; return false; });
s.keyDown(16); s.reset(true); await s.runFor(2_000_000); s.keyUp(16);
await s.runFor(3_000_000);
console.log(`writes to $${watch.toString(16)} (${process.argv[2] ?? "wcy"}):`, hits.join(" | "));
process.exit(0);
