#!/usr/bin/env python3
"""Build an Acorn DFS single-sided disc image (.ssd) from a list of files.

usage: mkdfs.py out.ssd title  name:path[:load[:exec]] ...
"""
import sys, struct

def build(out, title, files, boot=3):
    sectors = 800   # 80 tracks * 10 sectors
    cat0 = bytearray(256)
    cat1 = bytearray(256)
    cat0[0:8] = title[:8].ljust(8).encode()
    cat1[0:4] = title[8:12].ljust(4).encode()
    cat1[4] = 1                                   # cycle
    cat1[5] = len(files) * 8
    cat1[6] = ((boot & 3) << 4) | ((sectors >> 8) & 3)
    cat1[7] = sectors & 255
    img = bytearray(sectors * 256)
    # allocate sectors starting at 2, files listed in catalogue in descending start-sector order
    entries = []
    sec = 2
    for (name, data, load, exe) in files:
        start = sec
        nsec = (len(data) + 255) // 256
        img[start * 256:start * 256 + len(data)] = data
        sec += nsec
        entries.append((name, load, exe, len(data), start))
    assert sec <= sectors, 'disc full'
    entries.sort(key=lambda e: -e[4])
    for i, (name, load, exe, length, start) in enumerate(entries):
        d = '$'
        if '.' in name:
            d, name = name.split('.', 1)
        o = 8 + i * 8
        cat0[o:o + 7] = name[:7].ljust(7).encode()
        cat0[o + 7] = ord(d)
        cat1[o] = load & 255
        cat1[o + 1] = (load >> 8) & 255
        cat1[o + 2] = exe & 255
        cat1[o + 3] = (exe >> 8) & 255
        cat1[o + 4] = length & 255
        cat1[o + 5] = (length >> 8) & 255
        cat1[o + 6] = (((exe >> 16) & 3) << 6) | (((length >> 16) & 3) << 4) | (((load >> 16) & 3) << 2) | ((start >> 8) & 3)
        cat1[o + 7] = start & 255
    img[0:256] = cat0
    img[256:512] = cat1
    open(out, 'wb').write(img)

def layout(files):
    """returns {name: (start_sector, nsectors)} using the same allocation as build()"""
    sec = 2
    res = {}
    for (name, data, load, exe) in files:
        nsec = (len(data) + 255) // 256
        res[name] = (sec, nsec)
        sec += nsec
    return res

if __name__ == '__main__':
    mode = sys.argv[1]
    if mode == 'table':
        out = sys.argv[2]
        files = []
        for spec in sys.argv[3:]:
            parts = spec.split(':')
            files.append((parts[0], open(parts[1], 'rb').read(), 0, 0))
        lay = layout(files)
        with open(out, 'w') as f:
            f.write('; generated by mkdfs.py table\n')
            for (name, data, load, exe) in files:
                sec, n = lay[name]
                ident = name.replace('!', 'BOOT').replace('$.', '')
                f.write('F_%s_SEC = %d\nF_%s_N = %d\n' % (ident, sec, ident, n))
        sys.exit(0)
    out, title = sys.argv[2], sys.argv[3]
    files = []
    for spec in sys.argv[4:]:
        parts = spec.split(':')
        name, path = parts[0], parts[1]
        load = int(parts[2], 16) if len(parts) > 2 else 0
        exe = int(parts[3], 16) if len(parts) > 3 else load
        files.append((name, open(path, 'rb').read(), load, exe))
    build(out, title, files)
