#!/bin/sh
# Cleo, Model B target: the Master's sources (../src) assembled with MODELB=1 and
# MODE1=1, this directory's own files, every level packed by tools/assets.py, and a
# disc the game loads itself from (docs/PLAN_MODELB_FULL.md).
set -e
cd "$(dirname "$0")"
mkdir -p build
[ -n "$SKIP_ASSETS" ] || python3 tools/assets.py

# the disc's file list, in disc order: what every load reads first (LDPROG) by the
# boot files, the shared files together, the levels after them
DISC="!BOOT:build/BOOT LOADER:build/LOADER BANKS:build/BANKS LDPROG:build/LDPROG MENU:build/MENU BAR:build/BAR"
DISC="$DISC SPR:../build/SPR SPRAND:../build/SPRAND BOX:../build/BOX TILESO:../build/TILESO TILESI:../build/TILESI TITLE:../build/TITLE"
for l in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do DISC="$DISC L$l:build/L$l"; done
for f in BOOT LOADER BANKS MENU LDPROG; do [ -f build/$f ] || : > build/$f; done
printf '*RUN LOADER\r' > build/BOOT

# Two passes: the sector table (files.inc) needs the files' sizes, and bank 7 and
# LDPROG carry entries from it.  No size depends on a sector number, so the second
# pass is stable (the third checks that).
for pass in 1 2 3; do
    [ $pass = 3 ] && cp build/files.inc build/files.prev
    python3 ../tools/mkdfs.py table build/files.inc $DISC
    [ $pass = 3 ] && { cmp -s build/files.inc build/files.prev || { echo "files.inc did not settle"; exit 1; }; break; }
    # the include order matters: this target's build/ and src/ before the Master's src/
    ca65 -g --cpu 6502 -D MODELB=1 -D MODE1=1 -I build -I src -I ../src \
         -o build/main.o src/main.s -l build/main.lst
    ld65 -C cleo_b.cfg -o build/unused.bin build/main.o -m build/map.txt -Ln build/labels.txt
    # what the loaders need from the game: its addresses
    python3 - <<'EOF'
import re
want = ['BANKCODE','dsk_type','dsk_drv','read_sectors','ld_sec','ld_n','ld_dst',
        'LV_HDR','LV_OBJS','LV_ATTR0','LV_ALTCLS','TILES','SPRMASK','sprtab','mapshr','MAPSTRIDE','FLATTAB',
        'half0','half1','half2','halfhi','halfsub','HPAIR0','HPAIR1',
        'MENU_BASE','TITLE_ADDR','MAP6','BARADDR','STAGE','STAGE_LVL','LDPROG','PBANK','dsk_banks']
addr = {}
for l in open('build/labels.txt'):
    p = l.split()
    if len(p) >= 3 and p[0] == 'al':
        addr[p[2].lstrip('.')] = int(p[1], 16)
with open('build/defs_ld.inc', 'w') as f:
    f.write('; generated by build.sh from build/labels.txt\n')
    for n in want:
        if n in addr:
            f.write('%s = $%04X\n' % (n, addr[n]))
        else:
            f.write('; %s: not in labels.txt (a constant?)\n' % n)
EOF
    # the constants ld65 does not list
    grep -E '^(MENU_BASE|TILES|NMIPAGE|LDPROG|STAGE|STAGE_LVL|TITLE_ADDR|MAP6|BANKCODE|LV_OBJS)\s*=' src/defs.inc build/assets.inc \
        | sed 's/^[^:]*://; s/;.*//' >> build/defs_ld.inc
    echo 'BARADDR = $0300' >> build/defs_ld.inc
    ca65 --cpu 6502 -I build -I src -o build/ldprog.o src/ldprog.s -l build/ldprog.lst
    ld65 -C ldprog.cfg -o build/LDPROG build/ldprog.o
    ca65 --cpu 6502 -I build -I src -o build/loader.o src/loader.s
    ld65 -C loader.cfg -o build/LOADER build/loader.o
    # BANKS: the fixed pieces with their table, then the bank-number patch list (every
    # byte of the pieces that holds a bank number, cpu.inc BANKREF) ending in $FF: the
    # boot loader rewrites those bytes to the banks it found RAM in.  Each entry is
    # checked against the pieces here: a wrong bank on a bankimm would land outside
    # them or on a byte that is no bank number.
    python3 - <<'EOF'
import os
pieces = [(4, 0x8000, 'b4c.bin'), (4, 0x8300, 'b4t.bin'), (4, 0xBBE0, 'b4x.bin'),
          (5, 0x8000, 'b5c.bin'), (5, 0xB620, 'b5x.bin'),         # (B5X in cleo_b.cfg)
          (6, 0x8000, 'b6c.bin'), (6, 0x8040, 'b6l.bin'), (6, 0x8400, 'b6t.bin'), (6, 0xBD60, 'b6x.bin'),
          (7, 0x8000, 'b7a.bin'), (7, 0x8520, 'b7.bin')]
tab, body, img = bytearray([len(pieces)]), bytearray(), {}
for bank, addr, fn in pieces:
    d = open(os.path.join('build', fn), 'rb').read()
    tab += bytes([bank, addr & 255, addr >> 8, len(d) & 255, len(d) >> 8])
    body += d
    img[(bank, addr)] = d
fix = open('build/bankfix.bin', 'rb').read()
assert len(fix) % 3 == 0, 'bankfix.bin is not whole entries'
for i in range(0, len(fix), 3):
    bank, addr = fix[i], fix[i + 1] | (fix[i + 2] << 8)
    hit = [d[addr - a] for (b, a), d in img.items() if b == bank and a <= addr < a + len(d)]
    assert len(hit) == 1, 'bank patch %d:$%04X is in no piece' % (bank, addr)
    assert 4 <= (hit[0] & 15) <= 7, 'bank patch %d:$%04X names byte $%02X, no bank number' % (bank, addr, hit[0])
open('build/BANKS', 'wb').write(tab + body + fix + b'\xff')
print('BANKS: %d pieces, %d bytes, %d bank patches' % (len(pieces), len(tab) + len(body), len(fix) // 3))
EOF
done
python3 ../tools/mkdfs.py build build/cleob.ssd CLEOB \
    '!BOOT:build/BOOT:0000:FFFF' 'LOADER:build/LOADER:1900:1900' \
    $(echo $DISC | tr ' ' '\n' | grep -v '^!BOOT\|^LOADER' | tr '\n' ' ')
ls -l build/BANKS build/MENU build/LDPROG build/cleob.ssd
