#!/bin/sh
# Cleo, Model B target: the Master's sources (../src) assembled with MODELB=1 and
# this directory's own files, every level packed by tools/assets.py, and a
# disc the game loads itself from (docs/PLAN_MODELB_FULL.md).
set -e
cd "$(dirname "$0")"
# TARGET=master builds the CONVERGED MASTER: this target's structure (the bank images,
# the loader, the far calls) on a Master's hardware -- 65C02, the 32-row ring in main
# and shadow RAM, the Master's interrupt handler and chain in main RAM, its 1770 --
# into buildm/cleom.ssd (src/cpu.inc: MODELB=1, BHW=0).
if [ "$TARGET" = master ]; then
    BD=buildm; CPU=65C02; DEFS="-D MODELB=1 -D BHW=0"; CFG=cleo_m.cfg; SSD=cleom; BARADDR='$2B00'
else
    BD=build; CPU=6502; DEFS="-D MODELB=1"; CFG=cleo_b.cfg; SSD=cleob; BARADDR='$0300'
fi
export BD TARGET
mkdir -p $BD
[ -n "$SKIP_ASSETS" ] || python3 tools/assets.py
sed "s#\"build/#\"$BD/#g" $CFG > $BD/game.cfg

# the disc's file list, in disc order: what every load reads first (LDPROG) by the
# boot files, the shared files together, the levels after them
DISC="!BOOT:$BD/BOOT LOADER:$BD/LOADER BANKS:$BD/BANKS LDPROG:$BD/LDPROG MENU:$BD/MENU BAR:$BD/BAR"
DISC="$DISC SPRX:$BD/SPRX SPRC:$BD/SPRC TILES0:../build/TILES0 TILES1:../build/TILES1 TITLE:../build/TITLE"
for l in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do DISC="$DISC L$l:$BD/L$l"; done
DISC="$DISC TILES2:../build/TILES2"
for f in BOOT LOADER BANKS MENU LDPROG; do [ -f $BD/$f ] || : > $BD/$f; done
printf '*RUN LOADER\r' > $BD/BOOT

# Two passes: the sector table (files.inc) needs the files' sizes, and bank 7 and
# LDPROG carry entries from it.  No size depends on a sector number, so the second
# pass is stable (the third checks that).
for pass in 1 2 3; do
    [ $pass = 3 ] && cp $BD/files.inc $BD/files.prev
    python3 ../tools/mkdfs.py table $BD/files.inc $DISC
    [ $pass = 3 ] && { cmp -s $BD/files.inc $BD/files.prev || { echo "files.inc did not settle"; exit 1; }; break; }
    # the include order matters: this target's build/ and src/ before the Master's src/
    ca65 -g --cpu $CPU $DEFS -I $BD -I src -I ../src \
         -o $BD/main.o src/main.s -l $BD/main.lst
    ld65 -C $BD/game.cfg -o $BD/unused.bin $BD/main.o -m $BD/map.txt -Ln $BD/labels.txt --dbgfile $BD/cleo.dbg
    # what the loaders need from the game: its addresses
    python3 - <<'EOF'
import re
want = ['BANKCODE','dsk_type','dsk_drv','read_sectors','ld_sec','ld_n','ld_dst',
        'LV_HDR','LV_OBJS','LV_ATTR0','LV_ALTCLS','TILES','SPRMASK','sprtab','mapshr','MAPSTRIDE','FLATTAB',
        'half0','half1','half2','halfhi','halfsub','mir0','MIRTAB','sprc_ok','sprx_ok','HPAIR0','HPAIR1',
        'MENU_BASE','TITLE_ADDR','MAP6','BARADDR','STAGE','STAGE_LVL','LDPROG','PBANK','PBOARD','dsk_banks','dsk_board']
addr = {}
import os
BD = os.environ['BD']
for l in open(BD + '/labels.txt'):
    p = l.split()
    if len(p) >= 3 and p[0] == 'al':
        addr[p[2].lstrip('.')] = int(p[1], 16)
with open(BD + '/defs_ld.inc', 'w') as f:
    f.write('; generated by build.sh from build/labels.txt\n')
    for n in want:
        if n in addr:
            f.write('%s = $%04X\n' % (n, addr[n]))
        else:
            f.write('; %s: not in labels.txt (a constant?)\n' % n)
EOF
    # the constants ld65 does not list: assembled with the game's own flags, so the
    # hardware conditionals in defs.inc resolve as they do in the game (src/ldconst.s)
    ca65 --cpu $CPU $DEFS -I $BD -I src -I ../src -o /dev/null src/ldconst.s > $BD/ldconst.out
    grep ' = ' $BD/ldconst.out >> $BD/defs_ld.inc
    grep '^al ' $BD/ldconst.out >> $BD/labels.txt
    echo "BARADDR = $BARADDR" >> $BD/defs_ld.inc
    ca65 --cpu 6502 $DEFS -I $BD -I src -o $BD/ldprog.o src/ldprog.s -l $BD/ldprog.lst
    ld65 -C ldprog.cfg -o $BD/LDPROG $BD/ldprog.o
    ca65 --cpu 6502 $DEFS -I $BD -I src -o $BD/loader.o src/loader.s
    ld65 -C loader.cfg -o $BD/LOADER $BD/loader.o
    # BANKS: the fixed pieces with their table, then the bank-number patch list (every
    # byte of the pieces that holds a bank number, cpu.inc BANKREF) ending in $FF: the
    # boot loader rewrites those bytes to the banks it found RAM in.  Each entry is
    # checked against the pieces here: a wrong bank on a bankimm would land outside
    # them or on a byte that is no bank number.  Then the write-bank store list (cpu.inc
    # wrsel: bank, address, kind; every entry must sit on a `sta $FE30`), ending in $FF.
    python3 - <<'EOF'
import os
BD = os.environ['BD']
pieces = [(4, 0x8000, 'b4c.bin'), (4, 0x8300, 'b4t.bin'), (4, 0xBC40, 'b4x.bin'),
          (5, 0x8000, 'b5c.bin'), (5, 0xB620, 'b5x.bin'),         # (B5X in cleo_b.cfg)
          (6, 0x8000, 'b6c.bin'), (6, 0x8040, 'b6l.bin'), (6, 0x8400, 'b6t.bin'), (6, 0xBDA0, 'b6x.bin'),
          (7, 0x8000, 'b7a.bin'), (7, 0x8520, 'b7.bin')]
if os.environ.get('TARGET') == 'master':
    pieces.append((7, 0x0600, 'mcode.bin'))         # main RAM: the Master's handler and chain
tab, body, img = bytearray([len(pieces)]), bytearray(), {}
for bank, addr, fn in pieces:
    d = open(os.path.join(BD, fn), 'rb').read()
    tab += bytes([bank, addr & 255, addr >> 8, len(d) & 255, len(d) >> 8])
    body += d
    img[(bank, addr)] = d
def piece_bytes(bank, addr, n):
    hit = [d[addr - a:addr - a + n] for (b, a), d in img.items() if b == bank and a <= addr and addr + n <= a + len(d)]
    assert len(hit) == 1, 'patch %d:$%04X is in no piece' % (bank, addr)
    return hit[0]
fix = open(BD + '/bankfix.bin', 'rb').read()
assert len(fix) % 3 == 0, 'bankfix.bin is not whole entries'
for i in range(0, len(fix), 3):
    bank, addr = fix[i], fix[i + 1] | (fix[i + 2] << 8)
    v = piece_bytes(bank, addr, 1)[0]
    assert 4 <= (v & 15) <= 7, 'bank patch %d:$%04X names byte $%02X, no bank number' % (bank, addr, v)
wr = open(BD + '/wrfix.bin', 'rb').read()
assert len(wr) % 4 == 0, 'wrfix.bin is not whole entries'
for i in range(0, len(wr), 4):
    bank, addr, kind = wr[i], wr[i + 1] | (wr[i + 2] << 8), wr[i + 3]
    assert piece_bytes(bank, addr, 3) == b'\x8d\x30\xfe', 'write-bank store %d:$%04X is not sta $FE30' % (bank, addr)
    assert kind in (4, 5, 6, 7, 0xFE), 'write-bank store %d:$%04X: kind $%02X' % (bank, addr, kind)
open(BD + '/BANKS', 'wb').write(tab + body + fix + b'\xff' + wr + b'\xff')
print('BANKS: %d pieces, %d bytes, %d bank patches, %d write-bank stores' % (len(pieces), len(tab) + len(body), len(fix) // 3, len(wr) // 4))
EOF
done
python3 ../tools/mkdfs.py build $BD/$SSD.ssd CLEOB \
    "!BOOT:$BD/BOOT:0000:FFFF" "LOADER:$BD/LOADER:1900:1900" \
    $(echo $DISC | tr ' ' '\n' | grep -v '^!BOOT\|^LOADER' | tr '\n' ' ')
ls -l $BD/BANKS $BD/MENU $BD/LDPROG $BD/$SSD.ssd
